#!/bin/bash
iptables -A INPUT -m geoip --src-cc A1 -j DROP &&
iptables -A INPUT -m geoip --src-cc A2 -j DROP &&
iptables -A INPUT -m geoip --src-cc AD -j DROP &&
iptables -A INPUT -m geoip --src-cc AE -j DROP &&
iptables -A INPUT -m geoip --src-cc AF -j DROP &&
iptables -A INPUT -m geoip --src-cc AG -j DROP &&
iptables -A INPUT -m geoip --src-cc AI -j DROP &&
iptables -A INPUT -m geoip --src-cc AL -j DROP &&
iptables -A INPUT -m geoip --src-cc AM -j DROP &&
iptables -A INPUT -m geoip --src-cc AO -j DROP &&
iptables -A INPUT -m geoip --src-cc AQ -j DROP &&
iptables -A INPUT -m geoip --src-cc AR -j DROP &&
iptables -A INPUT -m geoip --src-cc AS -j DROP &&
iptables -A INPUT -m geoip --src-cc AT -j DROP &&
iptables -A INPUT -m geoip --src-cc AU -j DROP &&
iptables -A INPUT -m geoip --src-cc AW -j DROP &&
iptables -A INPUT -m geoip --src-cc AX -j DROP &&
iptables -A INPUT -m geoip --src-cc AZ -j DROP &&
iptables -A INPUT -m geoip --src-cc BA -j DROP &&
iptables -A INPUT -m geoip --src-cc BB -j DROP &&
iptables -A INPUT -m geoip --src-cc BD -j DROP &&
iptables -A INPUT -m geoip --src-cc BE -j DROP &&
iptables -A INPUT -m geoip --src-cc BF -j DROP &&
iptables -A INPUT -m geoip --src-cc BG -j DROP &&
iptables -A INPUT -m geoip --src-cc BH -j DROP &&
iptables -A INPUT -m geoip --src-cc BI -j DROP &&
iptables -A INPUT -m geoip --src-cc BJ -j DROP &&
iptables -A INPUT -m geoip --src-cc BM -j DROP &&
iptables -A INPUT -m geoip --src-cc BN -j DROP &&
iptables -A INPUT -m geoip --src-cc BO -j DROP &&
iptables -A INPUT -m geoip --src-cc BS -j DROP &&
iptables -A INPUT -m geoip --src-cc BT -j DROP &&
iptables -A INPUT -m geoip --src-cc BW -j DROP &&
iptables -A INPUT -m geoip --src-cc BY -j DROP &&
iptables -A INPUT -m geoip --src-cc BZ -j DROP &&
iptables -A INPUT -m geoip --src-cc CA -j DROP &&
iptables -A INPUT -m geoip --src-cc CD -j DROP &&
iptables -A INPUT -m geoip --src-cc CF -j DROP &&
iptables -A INPUT -m geoip --src-cc CG -j DROP &&
iptables -A INPUT -m geoip --src-cc CH -j DROP &&
iptables -A INPUT -m geoip --src-cc CI -j DROP &&
iptables -A INPUT -m geoip --src-cc CK -j DROP &&
iptables -A INPUT -m geoip --src-cc CL -j DROP &&
iptables -A INPUT -m geoip --src-cc CM -j DROP &&
iptables -A INPUT -m geoip --src-cc CN -j DROP &&
iptables -A INPUT -m geoip --src-cc CO -j DROP &&
iptables -A INPUT -m geoip --src-cc CR -j DROP &&
iptables -A INPUT -m geoip --src-cc CU -j DROP &&
iptables -A INPUT -m geoip --src-cc CV -j DROP &&
iptables -A INPUT -m geoip --src-cc CY -j DROP &&
iptables -A INPUT -m geoip --src-cc CZ -j DROP &&
iptables -A INPUT -m geoip --src-cc DE -j DROP &&
iptables -A INPUT -m geoip --src-cc DJ -j DROP &&
iptables -A INPUT -m geoip --src-cc DK -j DROP &&
iptables -A INPUT -m geoip --src-cc DM -j DROP &&
iptables -A INPUT -m geoip --src-cc DO -j DROP &&
iptables -A INPUT -m geoip --src-cc DZ -j DROP &&
iptables -A INPUT -m geoip --src-cc EC -j DROP &&
iptables -A INPUT -m geoip --src-cc EE -j DROP &&
iptables -A INPUT -m geoip --src-cc EG -j DROP &&
iptables -A INPUT -m geoip --src-cc ER -j DROP &&
iptables -A INPUT -m geoip --src-cc ES -j DROP &&
iptables -A INPUT -m geoip --src-cc ET -j DROP &&
iptables -A INPUT -m geoip --src-cc EU -j DROP &&
iptables -A INPUT -m geoip --src-cc FI -j DROP &&
iptables -A INPUT -m geoip --src-cc FJ -j DROP &&
iptables -A INPUT -m geoip --src-cc FK -j DROP &&
iptables -A INPUT -m geoip --src-cc FM -j DROP &&
iptables -A INPUT -m geoip --src-cc FO -j DROP &&
iptables -A INPUT -m geoip --src-cc FR -j DROP &&
iptables -A INPUT -m geoip --src-cc GA -j DROP &&
iptables -A INPUT -m geoip --src-cc GB -j DROP &&
iptables -A INPUT -m geoip --src-cc GD -j DROP &&
iptables -A INPUT -m geoip --src-cc GE -j DROP &&
iptables -A INPUT -m geoip --src-cc GF -j DROP &&
iptables -A INPUT -m geoip --src-cc GG -j DROP &&
iptables -A INPUT -m geoip --src-cc GH -j DROP &&
iptables -A INPUT -m geoip --src-cc GI -j DROP &&
iptables -A INPUT -m geoip --src-cc GL -j DROP &&
iptables -A INPUT -m geoip --src-cc GM -j DROP &&
iptables -A INPUT -m geoip --src-cc GN -j DROP &&
iptables -A INPUT -m geoip --src-cc GP -j DROP &&
iptables -A INPUT -m geoip --src-cc GQ -j DROP &&
iptables -A INPUT -m geoip --src-cc GR -j DROP &&
iptables -A INPUT -m geoip --src-cc GT -j DROP &&
iptables -A INPUT -m geoip --src-cc GU -j DROP &&
iptables -A INPUT -m geoip --src-cc GW -j DROP &&
iptables -A INPUT -m geoip --src-cc GY -j DROP &&
iptables -A INPUT -m geoip --src-cc HK -j DROP &&
iptables -A INPUT -m geoip --src-cc HN -j DROP &&
iptables -A INPUT -m geoip --src-cc HR -j DROP &&
iptables -A INPUT -m geoip --src-cc HT -j DROP &&
iptables -A INPUT -m geoip --src-cc HU -j DROP &&
iptables -A INPUT -m geoip --src-cc ID -j DROP &&
iptables -A INPUT -m geoip --src-cc IE -j DROP &&
iptables -A INPUT -m geoip --src-cc IL -j DROP &&
iptables -A INPUT -m geoip --src-cc IM -j DROP &&
iptables -A INPUT -m geoip --src-cc IN -j DROP &&
iptables -A INPUT -m geoip --src-cc IO -j DROP &&
iptables -A INPUT -m geoip --src-cc IQ -j DROP &&
iptables -A INPUT -m geoip --src-cc IR -j DROP &&
iptables -A INPUT -m geoip --src-cc IS -j DROP &&
iptables -A INPUT -m geoip --src-cc IT -j DROP &&
iptables -A INPUT -m geoip --src-cc JE -j DROP &&
iptables -A INPUT -m geoip --src-cc JM -j DROP &&
iptables -A INPUT -m geoip --src-cc JO -j DROP &&
iptables -A INPUT -m geoip --src-cc JP -j DROP &&
iptables -A INPUT -m geoip --src-cc KE -j DROP &&
iptables -A INPUT -m geoip --src-cc KG -j DROP &&
iptables -A INPUT -m geoip --src-cc KH -j DROP &&
iptables -A INPUT -m geoip --src-cc KI -j DROP &&
iptables -A INPUT -m geoip --src-cc KM -j DROP &&
iptables -A INPUT -m geoip --src-cc KN -j DROP &&
iptables -A INPUT -m geoip --src-cc KP -j DROP &&
iptables -A INPUT -m geoip --src-cc KR -j DROP &&
iptables -A INPUT -m geoip --src-cc KW -j DROP &&
iptables -A INPUT -m geoip --src-cc KY -j DROP &&
iptables -A INPUT -m geoip --src-cc KZ -j DROP &&
iptables -A INPUT -m geoip --src-cc LA -j DROP &&
iptables -A INPUT -m geoip --src-cc LB -j DROP &&
iptables -A INPUT -m geoip --src-cc LC -j DROP &&
iptables -A INPUT -m geoip --src-cc LI -j DROP &&
iptables -A INPUT -m geoip --src-cc LK -j DROP &&
iptables -A INPUT -m geoip --src-cc LR -j DROP &&
iptables -A INPUT -m geoip --src-cc LS -j DROP &&
iptables -A INPUT -m geoip --src-cc LT -j DROP &&
iptables -A INPUT -m geoip --src-cc LU -j DROP &&
iptables -A INPUT -m geoip --src-cc LV -j DROP &&
iptables -A INPUT -m geoip --src-cc LY -j DROP &&
iptables -A INPUT -m geoip --src-cc MA -j DROP &&
iptables -A INPUT -m geoip --src-cc MC -j DROP &&
iptables -A INPUT -m geoip --src-cc MD -j DROP &&
iptables -A INPUT -m geoip --src-cc ME -j DROP &&
iptables -A INPUT -m geoip --src-cc MF -j DROP &&
iptables -A INPUT -m geoip --src-cc MG -j DROP &&
iptables -A INPUT -m geoip --src-cc MH -j DROP &&
iptables -A INPUT -m geoip --src-cc MK -j DROP &&
iptables -A INPUT -m geoip --src-cc ML -j DROP &&
iptables -A INPUT -m geoip --src-cc MM -j DROP &&
iptables -A INPUT -m geoip --src-cc MN -j DROP &&
iptables -A INPUT -m geoip --src-cc MO -j DROP &&
iptables -A INPUT -m geoip --src-cc MP -j DROP &&
iptables -A INPUT -m geoip --src-cc MQ -j DROP &&
iptables -A INPUT -m geoip --src-cc MR -j DROP &&
iptables -A INPUT -m geoip --src-cc MS -j DROP &&
iptables -A INPUT -m geoip --src-cc MT -j DROP &&
iptables -A INPUT -m geoip --src-cc MU -j DROP &&
iptables -A INPUT -m geoip --src-cc MV -j DROP &&
iptables -A INPUT -m geoip --src-cc MW -j DROP &&
iptables -A INPUT -m geoip --src-cc MX -j DROP &&
iptables -A INPUT -m geoip --src-cc MY -j DROP &&
iptables -A INPUT -m geoip --src-cc MZ -j DROP &&
iptables -A INPUT -m geoip --src-cc NA -j DROP &&
iptables -A INPUT -m geoip --src-cc NC -j DROP &&
iptables -A INPUT -m geoip --src-cc NE -j DROP &&
iptables -A INPUT -m geoip --src-cc NF -j DROP &&
iptables -A INPUT -m geoip --src-cc NG -j DROP &&
iptables -A INPUT -m geoip --src-cc NI -j DROP &&
iptables -A INPUT -m geoip --src-cc NL -j DROP &&
iptables -A INPUT -m geoip --src-cc NO -j DROP &&
iptables -A INPUT -m geoip --src-cc NP -j DROP &&
iptables -A INPUT -m geoip --src-cc NR -j DROP &&
iptables -A INPUT -m geoip --src-cc NU -j DROP &&
iptables -A INPUT -m geoip --src-cc NZ -j DROP &&
iptables -A INPUT -m geoip --src-cc OM -j DROP &&
iptables -A INPUT -m geoip --src-cc PA -j DROP &&
iptables -A INPUT -m geoip --src-cc PE -j DROP &&
iptables -A INPUT -m geoip --src-cc PF -j DROP &&
iptables -A INPUT -m geoip --src-cc PG -j DROP &&
iptables -A INPUT -m geoip --src-cc PH -j DROP &&
iptables -A INPUT -m geoip --src-cc PK -j DROP &&
iptables -A INPUT -m geoip --src-cc PL -j DROP &&
iptables -A INPUT -m geoip --src-cc PM -j DROP &&
iptables -A INPUT -m geoip --src-cc PR -j DROP &&
iptables -A INPUT -m geoip --src-cc PS -j DROP &&
iptables -A INPUT -m geoip --src-cc PT -j DROP &&
iptables -A INPUT -m geoip --src-cc PW -j DROP &&
iptables -A INPUT -m geoip --src-cc PY -j DROP &&
iptables -A INPUT -m geoip --src-cc QA -j DROP &&
iptables -A INPUT -m geoip --src-cc RE -j DROP &&
iptables -A INPUT -m geoip --src-cc RO -j DROP &&
iptables -A INPUT -m geoip --src-cc RS -j DROP &&
iptables -A INPUT -m geoip --src-cc RU -j DROP &&
iptables -A INPUT -m geoip --src-cc RW -j DROP &&
iptables -A INPUT -m geoip --src-cc SA -j DROP &&
iptables -A INPUT -m geoip --src-cc SB -j DROP &&
iptables -A INPUT -m geoip --src-cc SC -j DROP &&
iptables -A INPUT -m geoip --src-cc SD -j DROP &&
iptables -A INPUT -m geoip --src-cc SE -j DROP &&
iptables -A INPUT -m geoip --src-cc SG -j DROP &&
iptables -A INPUT -m geoip --src-cc SI -j DROP &&
iptables -A INPUT -m geoip --src-cc SK -j DROP &&
iptables -A INPUT -m geoip --src-cc SL -j DROP &&
iptables -A INPUT -m geoip --src-cc SM -j DROP &&
iptables -A INPUT -m geoip --src-cc SN -j DROP &&
iptables -A INPUT -m geoip --src-cc SO -j DROP &&
iptables -A INPUT -m geoip --src-cc SR -j DROP &&
iptables -A INPUT -m geoip --src-cc ST -j DROP &&
iptables -A INPUT -m geoip --src-cc SV -j DROP &&
iptables -A INPUT -m geoip --src-cc SY -j DROP &&
iptables -A INPUT -m geoip --src-cc SZ -j DROP &&
iptables -A INPUT -m geoip --src-cc TC -j DROP &&
iptables -A INPUT -m geoip --src-cc TD -j DROP &&
iptables -A INPUT -m geoip --src-cc TG -j DROP &&
iptables -A INPUT -m geoip --src-cc TH -j DROP &&
iptables -A INPUT -m geoip --src-cc TJ -j DROP &&
iptables -A INPUT -m geoip --src-cc TK -j DROP &&
iptables -A INPUT -m geoip --src-cc TL -j DROP &&
iptables -A INPUT -m geoip --src-cc TM -j DROP &&
iptables -A INPUT -m geoip --src-cc TN -j DROP &&
iptables -A INPUT -m geoip --src-cc TO -j DROP &&
iptables -A INPUT -m geoip --src-cc TR -j DROP &&
iptables -A INPUT -m geoip --src-cc TT -j DROP &&
iptables -A INPUT -m geoip --src-cc TV -j DROP &&
iptables -A INPUT -m geoip --src-cc TW -j DROP &&
iptables -A INPUT -m geoip --src-cc TZ -j DROP &&
iptables -A INPUT -m geoip --src-cc UA -j DROP &&
iptables -A INPUT -m geoip --src-cc UG -j DROP &&
iptables -A INPUT -m geoip --src-cc UM -j DROP &&
iptables -A INPUT -m geoip --src-cc US -j DROP &&
iptables -A INPUT -m geoip --src-cc UY -j DROP &&
iptables -A INPUT -m geoip --src-cc UZ -j DROP &&
iptables -A INPUT -m geoip --src-cc VA -j DROP &&
iptables -A INPUT -m geoip --src-cc VC -j DROP &&
iptables -A INPUT -m geoip --src-cc VE -j DROP &&
iptables -A INPUT -m geoip --src-cc VG -j DROP &&
iptables -A INPUT -m geoip --src-cc VI -j DROP &&
iptables -A INPUT -m geoip --src-cc VN -j DROP &&
iptables -A INPUT -m geoip --src-cc VU -j DROP &&
iptables -A INPUT -m geoip --src-cc WF -j DROP &&
iptables -A INPUT -m geoip --src-cc WS -j DROP &&
iptables -A INPUT -m geoip --src-cc YE -j DROP &&
iptables -A INPUT -m geoip --src-cc YT -j DROP &&
iptables -A INPUT -m geoip --src-cc ZA -j DROP &&
iptables -A INPUT -m geoip --src-cc ZM -j DROP &&
iptables -A INPUT -m geoip --src-cc ZW -j DROP
